### ISSUE TITLE
ips-classes-S2.txt should contain only ip classes

### ISSUE THREAD

**Issue by mcatany** [renderedtext/snippets#31]
Hi,

we were using `ips-classes-S2.txt` for some of ours network policies. But since some new lines containing comments and non ip-classes it hsa broken our IaC. We suggest to change:
```
# Application cluster
35.236.192.62
# Build servers
```
for 
`35.236.192.62/32`
So the format with other files is homogeneous.

**Comment by mateuscap** [comment]
Hi there,

Thanks for the message! I just edited the file. :)
