### ISSUE TITLE
Invalid CIDR ranges included in ips-classes-S2.txt

### ISSUE THREAD

**Issue by jsnumerated** [renderedtext/snippets#35]
```
```
│ Error: "23.88.64.0/16" is not a valid IPv4 CIDR block; did you mean "23.88.0.0/16"?
│
│ Error: "38.23.46.0/20" is not a valid IPv4 CIDR block; did you mean "38.23.32.0/20"?

```

some systems/services do not care about validating CIDRs. AWS security group rules do

**Comment by jsnumerated** [comment]
there are ways around this (I was using terraform and they provide a cidrsubnet function that can be used to trim appropriately) but a valid CIDR range is probably better here

**Comment by mateuscap** [comment]
Thanks for creating this issue @jsnumerated. I've just updated the list, considering your report.
